import type { FileSystemTree, DirectoryNode, FileNode } from '@webcontainer/api';
import { flattenFileTree } from '../utils/context';
import { IntentClassifier } from './IntentClassifier';
import { FastLaneAI } from './FastLaneAI';
import { JulesClient } from './JulesClient';

export class AIOrchestrator {
  static async parseUserCommand(input: string, currentFileTree: FileSystemTree): Promise<FileSystemTree | null> {
    console.log('AIOrchestrator: Processing command:', input);

    try {
        // 1. Classify Intent
        const intent = await IntentClassifier.classifyIntent(input);
        console.log('AIOrchestrator: Intent classified as:', intent);

        if (intent === 'FAST_LANE') {
            const fileContext = flattenFileTree(currentFileTree);
            const modifiedFiles = await FastLaneAI.generateInstantEdit(input, fileContext);

            if (!modifiedFiles || modifiedFiles.length === 0) {
                console.log('AIOrchestrator: No changes generated by FastLaneAI.');
                return null; // Or return original tree? null indicates no change in existing logic
            }

            // Apply changes to tree
            const newTree = JSON.parse(JSON.stringify(currentFileTree));
            for (const file of modifiedFiles) {
                this.updateFileInTree(newTree, file.path, file.newContent);
            }
            return newTree;
        } else {
            // HEAVY_LANE -> Jules
            // JulesClient returns the full updated tree
            return await JulesClient.syncAndSolve(input, currentFileTree);
        }
    } catch (error) {
        console.error('AIOrchestrator: Error processing command', error);
        return null;
    }
  }

  private static updateFileInTree(tree: FileSystemTree, filePath: string, newContent: string) {
    const parts = filePath.split('/');
    let currentLevel = tree;

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (i === parts.length - 1) {
        // File
        const node = currentLevel[part] as any;
        if (node && 'file' in node) {
          (node as FileNode).file.contents = newContent;
        } else {
             // Create if not exists
             currentLevel[part] = {
                 file: {
                     contents: newContent
                 }
             };
        }
      } else {
        // Directory
        const node = currentLevel[part] as any;
        if (node && 'directory' in node) {
          currentLevel = (node as DirectoryNode).directory;
        } else {
           // Create directory if missing
           currentLevel[part] = { directory: {} };
           currentLevel = (currentLevel[part] as DirectoryNode).directory;
        }
      }
    }
  }
}
